// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AddFiles(arg1:Array<string>):Promise<Array<main.FileView>>;

export function ClearFiles():Promise<Array<main.FileView>>;

export function ComputePreview(arg1:main.PlanOptions):Promise<Array<main.FileView>>;

export function ExecuteRename(arg1:main.PlanOptions):Promise<{[key: string]: any}>;

export function GetConfig():Promise<config.Config>;

export function Greet(arg1:string):Promise<string>;

export function Install():Promise<void>;

export function RemoveFile(arg1:string):Promise<Array<main.FileView>>;

export function Revert():Promise<{[key: string]: any}>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function Uninstall():Promise<void>;

export function View():Promise<Array<main.FileView>>;
