// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function ClearFiles() {
  return window['go']['main']['App']['ClearFiles']();
}

export function ComputePreview(arg1) {
  return window['go']['main']['App']['ComputePreview'](arg1);
}

export function ExecuteRename(arg1) {
  return window['go']['main']['App']['ExecuteRename'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Install() {
  return window['go']['main']['App']['Install']();
}

export function RemoveFile(arg1) {
  return window['go']['main']['App']['RemoveFile'](arg1);
}

export function Revert() {
  return window['go']['main']['App']['Revert']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function Uninstall() {
  return window['go']['main']['App']['Uninstall']();
}

export function View() {
  return window['go']['main']['App']['View']();
}
